server:
    port: 8002
spring:
    application:
        name: spring-cloud-gateway
    profiles:
      active: dev
ribbon:
  ReadTimeout:  30000
  ConnectTimeout:  15000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000