eureka:
    client:
        serviceUrl:
            defaultZone: http://freeloop:freeloop@47.106.89.221:8000/eureka/
spring:
  redis:
    database: 3
    host: 139.9.48.215
    port: 6379
    password: 6379xk
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
  datasource:
    name: auth
    url: jdbc:mysql://139.9.48.215:3306/user
    username: root
    password: liduwangyi123!
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20