server:
    port: 8001
eureka:
    instance:
      hostname: discover
    client:
        serviceUrl:
            defaultZone: http://localhost:8000/eureka/
spring:
    application:
        name: spring-cloud-eureka