server:
    port: 8000
eureka:
    instance:
      hostname: discover
    client:
        serviceUrl:
            defaultZone: http://localhost:8001/eureka/
spring:
    application:
        name: spring-cloud-eureka