eureka:
    client:
        fetch-registry: false
        register-with-eureka: false
        serviceUrl:
            defaultZone: http://localhost:${server.port}/eureka/
server:
    port: 8000
spring:
    application:
        name: spring-cloud-eureka
    security:
        user:
            name: freeloop
            password: freeloop