eureka:
    client:
        fetch-registry: false
        register-with-eureka: false
        serviceUrl:
            defaultZone: http://freeloop:freeloop@localhost:8000/eureka/
server:
    port: 8001
spring:
    application:
        name: spring-cloud-eureka
    security:
        user:
            name: freeloop
            password: freeloop