server:
    port: 8001
eureka:
    instance:
      hostname: discover
    client:
        serviceUrl:
            defaultZone: http://freeloop:freeloop@localhost:8000/eureka/
spring:
    application:
        name: spring-cloud-eureka
    security:
        user:
            name: freeloop
            password: freeloop