eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8000/eureka/
spring:
  kafka:
    bootstrap-servers: 139.9.48.215:9092,139.9.49.150:9092,139.9.55.71:9092
    listener:
      concurrency: 10
    producer:
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
    consumer:
      # 默认消费者组
      group-id: xiaok1
      # 最早未被消费的offset
      auto-offset-reset: earliest
      # 批量一次最大拉取数据量
      max-poll-records: 100
      # 自动提交
      auto-commit-interval: 1000
      enable-auto-commit: true
      concurrency: 10