eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8000/eureka/
spring:
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      concurrency: 10
    producer:
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
    consumer:
      # 默认消费者组
      group-id: elk
      # 最早未被消费的offset
      auto-offset-reset: earliest
      # 批量一次最大拉取数据量
      max-poll-records: 100
      # 自动提交
      auto-commit-interval: 1000
      enable-auto-commit: true
      concurrency: 10
    # 消费者线程数(同一个组中消费者数不能高于区数)